### ISSUE TITLE
doesnt show in mozilla

### ISSUE THREAD

**Issue by ezraholm50** [ochameau/sabnzbdfox#5]
Hey, great app thanks! Although i cant get the icon to show anywhere in my firefox browser, after restart. Please help! Running ubuntu 15.04, latest firefox version and your latest app version.

**Comment by ezraholm50** [comment]
Anyone?

**Comment by hnz101** [comment]
It should show up now (after the last merge) as a toolbar Icon which you can position wherever you want.
